FROM rocker/tidyverse

RUN apt-get update -qq && apt-get -y --no-install-recommends install \
  libpython3-dev \
  python3-pip \
  && install2.r --error \
    --deps TRUE \
    reticulate
	fivethirtyeight
